### ISSUE TITLE
Hello I'am a memeber of chubaofs (now cubeFS), can you give the namespace back to us.

### ISSUE THREAD

**Issue by Huweicai** [0xhexchan/chubaofs-csi#1]
@0xlegendkiller

**Comment by 0xLegendKiller** [comment]
Sure, @Huweicai

**Comment by 0xLegendKiller** [comment]
I have changed my username, you can use the namespace.

Thanks, regards,
Aditya

**Comment by Huweicai** [comment]
Very thanks for cooperation, you are very cool.
